---
- name: Configure MyCloud
  hosts: mycloud
  remote_user: root
  vars:
    - mycloud_path: j
  tasks:
  - name: Create NGINX user
    ansible.builtin.user:
      name: nginx

  - name: Install Snap Dependencies
    ansible.builtin.snap:
      name: "{{ item }}"
    loop:
    - certbot

  - name: Install Apt Dependencies
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - unzip
    - unattended-upgrades

  - name: Install Deno
    shell: curl -fsSL https://deno.land/x/install/install.sh | sh

  - name: Add Deno to Bashrc
    ansible.builtin.lineinfile:
      path: /root/.bashrc
      line: "{{ item }}"
      create: yes
    loop:
    - export DENO_INSTALL="/root/.deno"
    - export PATH="$DENO_INSTALL/bin:$PATH"

  - name: Copy configuration and restart
    copy:
      src: /home/rg/Code/ws/axon/mycloud/assets/nginx.cfg
      dest: /etc/nginx/nginx.conf

  - name: Check NGINX configuration
    shell: nginx -t

  - name: Restart NGINX
    service:
      name: nginx
      state: restarted

  - name: Copy Common-Storage to the VM
    copy:
      src: /home/rg/Code/ws/axon/common-storage/src
      dest: /app/common-storage

  - name: Copy environmental variables to the vm
    copy:
      src: /home/rg/Code/ws/axon/mycloud/.app-env
      dest: /app/common-storage/.env

  - name: Copy Service File
    copy:
      src: /home/rg/Code/ws/axon/mycloud/assets/cs.service
      dest: /etc/systemd/system/cs.service

  - name: Start Common-Storage
    service:
      name: cs
      state: restarted
