---
- name: Configure MyCloud
  hosts: mycloud
  remote_user: root
  tasks:
  - name: Create NGINX user
    ansible.builtin.user:
      name: nginx

  - name: Install Snap Dependencies
    ansible.builtin.snap:
      name: "{{ item }}"
    loop:
    - certbot

  - name: Install Apt Dependencies
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
    - jo
    - jq
    - nginx
    - unattended-upgrades
    - unzip

  - name: Install Deno
    shell: curl -fsSL https://deno.land/x/install/install.sh | sh

  - name: Add Deno to Bashrc
    ansible.builtin.lineinfile:
      path: /root/.bashrc
      line: "{{ item }}"
      create: yes
    loop:
    - export DENO_INSTALL="/root/.deno"
    - export PATH="$DENO_INSTALL/bin:$PATH"

  - name: Copy configuration and restart
    copy:
      src: /home/rg/Code/ws/axon/mycloud/assets/nginx.cfg
      dest: /etc/nginx/nginx.conf

  - name: Check NGINX configuration
    shell: nginx -t

  - name: Restart NGINX
    service:
      name: nginx
      state: restarted

  - name:  Set timestamp
    set_fact:
      curr_time: "{{ ansible_date_time.epoch }}"

  - name: Copy Common-Storage Deployment to the VM
    copy:
      src: /home/rg/Code/ws/axon/common-storage/src
      dest: "/app/common-storage-{{ curr_time }}"

  - name: Copy environmental variables to the vm
    copy:
      src: /home/rg/Code/ws/axon/mycloud/.app-env
      dest: /app/common-storage-{{ curr_time }}/.env

  - name: Symlink the latest build to the active folder
    file:
      src: "/app/common-storage-{{ curr_time }}"
      dest: "/app/common-storage"
      state: link

  - name: Copy Service File
    copy:
      src: /home/rg/Code/ws/axon/mycloud/assets/cs.service
      dest: /etc/systemd/system/cs.service

  - name: Start Common-Storage
    service:
      name: cs
      state: restarted

  - name: Test Common-Storage using /feed
    shell: bash -c 'source /app/common-storage/.env && curl --user "$CS_USER:$CS_PASSWORD" "http://localhost:8080/feed" | jq .'

  - name: Create the /bookmarks topic
    shell:
      executable: /usr/bin/bash
      cmd: |
        source /app/common-storage/.env && curl -X POST -H "content-type: application/json;charset=utf-8" --data "$(jo -p description="borg bookmarks")" --user "$CS_USER:$CS_PASSWORD" "http://localhost:8080/topic/bookmarks"
